import type { AuctionItem } from '@/modules/auctions/types/auction.types';

export const mockAuctions: AuctionItem[] = [
  {
    id: 'daytona',
    title: 'Rolex Cosmograph Daytona 116500',
    category: 'Luxury Watches',
    description: 'A high-end luxury mechanical watch with an intricate skeleton dial, showcasing golden gears and complex movements. Mint condition, boxed with papers.',
    sku: 'WA-9902',
    currentBid: 34250,
    yourMaxBid: 36000,
    yourBid: 34250,
    totalBids: 42,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDevDKAQxS2pByG1MpmuQ05f3S96g6Icay09cHzcYCcs7yF5FAZxgh0Bl4f7ImbA0xcraxnceu0HTzi86ExeqpHzPgN3QNl6AQVUYrqC4lKskS7mONACQcDTNcXtU6xpLAv_w30j0a-4lyPQbMGc8JaUHyeR3sKGxznXDI7XOgeVUb0d3zaTyNz4vzrsSMtmG8v0Tr5eWnHcRYDZPbF1uFx9yOFJ6lqU5_vpsdWDiVP5ab0GvY2UCB4-I0jP8LYNSOYi5NDy0-VS5uV',
    timerSeconds: 18400,
    status: 'active',
    condition: 'New',
    sellerName: 'Timepiece Legends',
    sellerRating: 4.9,
    sellerSales: 1240,
    sellerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJMliNAX9iwfBs5w9IqD-A5JVNLkceWMpZoXHttDLkZEn9GsuALDInSRPSVqEUs5GGYq5hJYwIMcA_AEsIR1pYOZAPxg1w-vtbzAHQcf7Xd-KYn_4reIVsYn08Nby_mysL-pYseyUnxPuL1-2-zzQyhbrw04Sh2jQ6v-ljtHCyKHj_dYb8UR3pIPlo_bG9h3PKpf9ujxJ6NbQ1Srun08ibBUmXs7jnMImhAnexk1IjdciFq59YeCsye27wK9nsIfcg4_WF-qg4uy0v',
  },
  {
    id: 'ferrari',
    title: '2023 Ferrari F8 Tributo',
    category: 'Automotive',
    description: 'A sleek, modern red sports car parked in a minimalist, concrete architecture setting. Ambient low key lighting emphasizing its curves.',
    sku: 'CAR-F8-01',
    currentBid: 285000,
    totalBids: 18,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDDunc7gv41cYiFV_LdeVPPDF2T3G_Mrk7VGmhjc0_sr34xWxi0z-d6yHv6ynKP1dkju4LoMPyHqXx35JziUaNi15YvcZKp8PDVCjmhXj18-BlEwUKdfKpNNcc5Kr6xJD1B05IFLkBOpSXTu2FErDLYGqCh6dSzq8O7ZJVGAcqxMci0bGDra6_C0pAKeXU9vFc9i2-S5rSaAIEFkVK6qYwxC0AeO-qvqw-SGeyF4tBQxMIJm3GVMWjzRhtqK50zpm9OmNgl6LU08jiu',
    timerSeconds: 86400,
    status: 'active',
    condition: 'Used',
    sellerName: 'Exotic Wheels Inc.',
    sellerRating: 5.0,
    sellerSales: 340,
    sellerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJMliNAX9iwfBs5w9IqD-A5JVNLkceWMpZoXHttDLkZEn9GsuALDInSRPSVqEUs5GGYq5hJYwIMcA_AEsIR1pYOZAPxg1w-vtbzAHQcf7Xd-KYn_4reIVsYn08Nby_mysL-pYseyUnxPuL1-2-zzQyhbrw04Sh2jQ6v-ljtHCyKHj_dYb8UR3pIPlo_bG9h3PKpf9ujxJ6NbQ1Srun08ibBUmXs7jnMImhAnexk1IjdciFq59YeCsye27wK9nsIfcg4_WF-qg4uy0v',
  },
  {
    id: 'birkin',
    title: 'Hermès Birkin 30 Gold Epsom',
    category: 'Collectibles',
    description: 'Designer fashion accessories including a gold Epsom leather handbag. High key modern aesthetic, neutral and elegant tones.',
    sku: 'HB-EP-30',
    currentBid: 12800,
    totalBids: 29,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuChNuRQ4nBIoGC2AwfrfkDmflR3frXGQmR5s3ETL4KlGpLNU-R9DUn3pKw-xfhdQzhIwGrwXwLcQn8lVQB_9ybb2osS6MN7q3Haq8nDbBsEmvFai8o2XT4yzUNMzF9bJVyY_cnIMN2B0IjLhg70JpMC68ZBjhmefFtqxN2oNbaKhEu5i1y0klmTOLIng8p76v8v0huK5u7Ivi-mzg1WGWyUXTWrXbYhhi6rH1QodzArF51jFMAH06B0-xOBdLjcS_lum8vM-ZMBfyFo',
    timerSeconds: 3600,
    status: 'active',
    condition: 'New',
    sellerName: 'Couture Vault',
    sellerRating: 4.8,
    sellerSales: 512,
    sellerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJMliNAX9iwfBs5w9IqD-A5JVNLkceWMpZoXHttDLkZEn9GsuALDInSRPSVqEUs5GGYq5hJYwIMcA_AEsIR1pYOZAPxg1w-vtbzAHQcf7Xd-KYn_4reIVsYn08Nby_mysL-pYseyUnxPuL1-2-zzQyhbrw04Sh2jQ6v-ljtHCyKHj_dYb8UR3pIPlo_bG9h3PKpf9ujxJ6NbQ1Srun08ibBUmXs7jnMImhAnexk1IjdciFq59YeCsye27wK9nsIfcg4_WF-qg4uy0v',
  },
  {
    id: 'heritage-chrono',
    title: 'Heritage Automatic Chronograph',
    category: 'Luxury Watches',
    description: 'Mint condition, boxed with papers. Limited edition series. Intricate dial details, highly sought after model.',
    sku: 'WA-7712',
    currentBid: 4250,
    totalBids: 15,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAEi87bMnKhFHqJ3-zB0UuV6jek8iK5RePOJRXV62pmn0yIcl4v8EvDYcm-Ly55EYUuEciZN5oWWuibLFf4Sip57Ik2O_0b75GPA3RWubAg0gKLKgrgn2zTb8dlt_zamBRtVL2N9HW1AlE_8BEJw_IWbh_hbEwUmic1hFqKY3IXbqkjTDm7iz5bbUxyfDgqThvUCty4I2ey0N8HC-ijylmRVLpJGcJHnU7QISv1-lhrS4lBidJGqCXYBqgEpkJcLyZajyJ7svbRlwr2',
    timerSeconds: 8100,
    status: 'active',
    condition: 'Used',
    sellerName: 'Timepiece Legends',
    sellerRating: 4.9,
    sellerSales: 1240,
    sellerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJMliNAX9iwfBs5w9IqD-A5JVNLkceWMpZoXHttDLkZEn9GsuALDInSRPSVqEUs5GGYq5hJYwIMcA_AEsIR1pYOZAPxg1w-vtbzAHQcf7Xd-KYn_4reIVsYn08Nby_mysL-pYseyUnxPuL1-2-zzQyhbrw04Sh2jQ6v-ljtHCyKHj_dYb8UR3pIPlo_bG9h3PKpf9ujxJ6NbQ1Srun08ibBUmXs7jnMImhAnexk1IjdciFq59YeCsye27wK9nsIfcg4_WF-qg4uy0v',
    bidStatus: 'winning'
  },
  {
    id: 'ocean-diver',
    title: 'Vintage Ocean Diver 1974',
    category: 'Luxury Watches',
    description: 'Original patina, recently serviced movement. Collector\'s choice with authentic retro watch body and markers.',
    sku: 'WA-1974-V',
    currentBid: 1890,
    totalBids: 22,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDATFdzb8NFNijhCWTgOoUUtg9SQ1Q9aXllVA6u4ipxNgDKtjnVevBCmVMbAuZnbDJ4l_6oww2-WRJn4l5Ole9qg95ovXvmobnhOf8jigUO4ynKdNr2chSeV2KVp6Oia45IG4jrmU970S-Xl5XU0q6VKpBIoJQ_quUosgosIuwrgtoTrgm7kKFlhmksqhrezEeNUVEv_EYsaEW_k00aW_aYqJLVLzVdV_MxbmArMWBdVeGeA7CKFvJhUnfwaMHJ-gPKO46yxuxlwpT7',
    timerSeconds: 50700,
    status: 'active',
    condition: 'Used',
    sellerName: 'RetroHorology',
    sellerRating: 4.7,
    sellerSales: 48,
    sellerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJMliNAX9iwfBs5w9IqD-A5JVNLkceWMpZoXHttDLkZEn9GsuALDInSRPSVqEUs5GGYq5hJYwIMcA_AEsIR1pYOZAPxg1w-vtbzAHQcf7Xd-KYn_4reIVsYn08Nby_mysL-pYseyUnxPuL1-2-zzQyhbrw04Sh2jQ6v-ljtHCyKHj_dYb8UR3pIPlo_bG9h3PKpf9ujxJ6NbQ1Srun08ibBUmXs7jnMImhAnexk1IjdciFq59YeCsye27wK9nsIfcg4_WF-qg4uy0v',
    bidStatus: 'none'
  },
  {
    id: 'titan-skeleton',
    title: 'Titan Skeleton Concept',
    category: 'Luxury Watches',
    description: 'Visible movement, carbon fiber casing. Minimalist dark contemporary skeleton watch dial.',
    sku: 'WA-TIT-SK',
    currentBid: 8600,
    totalBids: 31,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuByfCkqOujvEdmy2-zAEdoFlsLGtUvvouDiSkCbEL0WpzEnY04flHcWBDHXsCUEYz76hw4BnUcwZoPGK81FgckpvpORBWnxx3n-PKFGqNQFF3zC7riH4BomzAo0yX7jAGe5cdGMPX7JQhVc437KuSM6y_C71EUFJ0DWV0qpmKsODDC8xxc1AhKCRdsUQVWiefB_dpf5tOaCdyV_-3lOoumnYicbda4csgB_sBcX4y5_hdPK1i9L9Frn50u8I29c3Slc0GjBJdjFdjIi',
    timerSeconds: 2880,
    status: 'active',
    condition: 'New',
    sellerName: 'FutureGear',
    sellerRating: 4.9,
    sellerSales: 219,
    sellerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJMliNAX9iwfBs5w9IqD-A5JVNLkceWMpZoXHttDLkZEn9GsuALDInSRPSVqEUs5GGYq5hJYwIMcA_AEsIR1pYOZAPxg1w-vtbzAHQcf7Xd-KYn_4reIVsYn08Nby_mysL-pYseyUnxPuL1-2-zzQyhbrw04Sh2jQ6v-ljtHCyKHj_dYb8UR3pIPlo_bG9h3PKpf9ujxJ6NbQ1Srun08ibBUmXs7jnMImhAnexk1IjdciFq59YeCsye27wK9nsIfcg4_WF-qg4uy0v',
    bidStatus: 'none'
  },
  {
    id: 'rose-gold',
    title: 'Elegance Rose Gold Mesh',
    category: 'Luxury Watches',
    description: 'Unworn condition. Beautiful rose gold watch with quick-release mesh strap.',
    sku: 'WA-RG-MS',
    currentBid: 720,
    totalBids: 9,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAxIRX1bzZTGUL7ol5IHdtkXaZxBp8WZSGHe0iFsxyy3bphheggfRyvgzD9ozyuY2eqKK-xX_Qq9w2R9JG1Vkc-rkNj8v4mo_7T46Rz1giv3TNttVGoxwIlA7p-LW762cHqckoy2awZrR8KxlP229ff8TZ34nwVxmOSPVptwq9OgmVT153yb186H64bPHgX_izibvbwPTvOFBvg4N9lABYuXRtuKJIsk1PyTbWAkXWRMH3TgmC0wCEjjotHRlUgnP3enehH3SBX03DN',
    timerSeconds: 186300,
    status: 'active',
    condition: 'New',
    sellerName: 'Couture Vault',
    sellerRating: 4.8,
    sellerSales: 512,
    sellerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJMliNAX9iwfBs5w9IqD-A5JVNLkceWMpZoXHttDLkZEn9GsuALDInSRPSVqEUs5GGYq5hJYwIMcA_AEsIR1pYOZAPxg1w-vtbzAHQcf7Xd-KYn_4reIVsYn08Nby_mysL-pYseyUnxPuL1-2-zzQyhbrw04Sh2jQ6v-ljtHCyKHj_dYb8UR3pIPlo_bG9h3PKpf9ujxJ6NbQ1Srun08ibBUmXs7jnMImhAnexk1IjdciFq59YeCsye27wK9nsIfcg4_WF-qg4uy0v',
    bidStatus: 'none'
  },
  {
    id: 'stealth-tactical',
    title: 'Stealth Tactical Series',
    category: 'Luxury Watches',
    description: 'Matte black titanium military-grade wristwatch. Water-resistant to 300m, high durability bezel.',
    sku: 'WA-ST-Tact',
    currentBid: 1150,
    totalBids: 14,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCmbjUrnadCLU2MD1eHpdU6_tnvQKMhkhZTOqq3883WNwYrPR7YXxK41w3HItBux31nnj5yyIaRndDdeRqZ2L3YNJBdW7K0yLWjObygSR6vgaz-0qqQ5cL3j28EaYGVnzaruTBpJQOhJfcrhqMsgeIkzpnDe5SUrL7fLqxZrAab1LzpK7Hm4NDJaAYYa8oI38o0P8R9lZTw2f0FKaQtZRrz9mITgyJP9fwTVWO_aIoR3ygf2eigPZvWcAWOjq6iHA4bUtvkl4cPGW6o',
    timerSeconds: 19300,
    status: 'active',
    condition: 'New',
    sellerName: 'FutureGear',
    sellerRating: 4.9,
    sellerSales: 219,
    sellerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJMliNAX9iwfBs5w9IqD-A5JVNLkceWMpZoXHttDLkZEn9GsuALDInSRPSVqEUs5GGYq5hJYwIMcA_AEsIR1pYOZAPxg1w-vtbzAHQcf7Xd-KYn_4reIVsYn08Nby_mysL-pYseyUnxPuL1-2-zzQyhbrw04Sh2jQ6v-ljtHCyKHj_dYb8UR3pIPlo_bG9h3PKpf9ujxJ6NbQ1Srun08ibBUmXs7jnMImhAnexk1IjdciFq59YeCsye27wK9nsIfcg4_WF-qg4uy0v',
    bidStatus: 'none'
  },
  {
    id: 'classic-gold',
    title: 'Classic Gold Dress Watch',
    category: 'Luxury Watches',
    description: '18k gold casing, crocodile leather brown strap. Exquisite luxury classic detailing.',
    sku: 'WA-CG-DS',
    currentBid: 12400,
    totalBids: 28,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCp3qPgatcnyKjaAbcZNh_s8qzxhp_DEe6YsNQfhK6zFIVLssRvlSU8an0I2bf8He5z_tozf3Uiz8PXXKvmzWDdRjROdHqLnF9VWsY4G_1WPcfsZGp4mXDdBMher61VoXuWfz1kG9g9VUdbEX0CgF6TYONr704-Gb0utZhPLf3MVfjjXAZe42DDZEGCQNg7k5u2aPq4ISrBefIa8fdR8aO1OhkRBV0Yz7fy-0V6kxUzo_pr8_UsnL6Ya0wJ3IDOKnLE_Aig12EO4dGP',
    timerSeconds: 80285,
    status: 'active',
    condition: 'Used',
    sellerName: 'Legacy Watches',
    sellerRating: 4.8,
    sellerSales: 1105,
    sellerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJMliNAX9iwfBs5w9IqD-A5JVNLkceWMpZoXHttDLkZEn9GsuALDInSRPSVqEUs5GGYq5hJYwIMcA_AEsIR1pYOZAPxg1w-vtbzAHQcf7Xd-KYn_4reIVsYn08Nby_mysL-pYseyUnxPuL1-2-zzQyhbrw04Sh2jQ6v-ljtHCyKHj_dYb8UR3pIPlo_bG9h3PKpf9ujxJ6NbQ1Srun08ibBUmXs7jnMImhAnexk1IjdciFq59YeCsye27wK9nsIfcg4_WF-qg4uy0v',
    bidStatus: 'none'
  },
  {
    id: 'leica-m11',
    title: 'Leica M11 Rangefinder Body',
    category: 'Collectibles',
    description: 'A classic black Leica rangefinder body. Iconic design for high-trust professional photographers and enthusiasts.',
    sku: 'CAM-M11',
    currentBid: 4250,
    totalBids: 11,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCVfB99XljmxF8Kw17HOFaX_CIxwnuBzGx8MRctbLf7rgC2UmeAmrQ0AlH5fr_e325h95hYLwCa-1Bshq7szkGi5bukex5RoUqN0w6C2vO4q71_8CLSZW8NS62DOaTKBmUogYasdjvMLw8xneXxUazm4mLtRnmDpDfUr9Q16gmDbKE914dTt-NByyPqeE2bfumI0j4feDI56OcFW-JG0NI8f91Ss6QjW7BNLmS7wVf9Vd285loKnb2BaBdkyGfR06k1SOD8WQy2F20F',
    timerSeconds: 8100,
    status: 'active',
    condition: 'Used',
    sellerName: 'Leica Specialist',
    sellerRating: 4.9,
    sellerSales: 160,
    sellerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJMliNAX9iwfBs5w9IqD-A5JVNLkceWMpZoXHttDLkZEn9GsuALDInSRPSVqEUs5GGYq5hJYwIMcA_AEsIR1pYOZAPxg1w-vtbzAHQcf7Xd-KYn_4reIVsYn08Nby_mysL-pYseyUnxPuL1-2-zzQyhbrw04Sh2jQ6v-ljtHCyKHj_dYb8UR3pIPlo_bG9h3PKpf9ujxJ6NbQ1Srun08ibBUmXs7jnMImhAnexk1IjdciFq59YeCsye27wK9nsIfcg4_WF-qg4uy0v',
  },
  {
    id: 'walnut-speakers',
    title: 'Restored 1970s Walnut Speakers',
    category: 'Collectibles',
    description: 'Beautifully restored wooden vintage high-fidelity speaker cabinets. Clean warm design and texture.',
    sku: 'SPK-WN-70',
    currentBid: 890,
    totalBids: 8,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCg-B_TCFe0z49BGeGBefQHwki7w8ICsAb-Tejk_ultMLY0JiAV18FjquyA5DR7qa3Zjw7ys3XOjskRH8YwLbQ1ahaHJvgATckLVBeCIOkJrR1sGVsHqRD0k2tnGKMDVem2LTlBc0RTswSCZDxCpvLT9nU12xemSn9yGC4lak-b9C45y4qDgiFoA5FEgzemoCeU_yuXa6Gsxw7yPHV3uJyT0GgU79coTHaAxQNKCubnhMX81jIY9G4TLXeB2hyUaGscoXBi1dDhAdWt',
    timerSeconds: 24000,
    status: 'active',
    condition: 'Used',
    sellerName: 'Audio Restoration',
    sellerRating: 4.8,
    sellerSales: 94,
    sellerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJMliNAX9iwfBs5w9IqD-A5JVNLkceWMpZoXHttDLkZEn9GsuALDInSRPSVqEUs5GGYq5hJYwIMcA_AEsIR1pYOZAPxg1w-vtbzAHQcf7Xd-KYn_4reIVsYn08Nby_mysL-pYseyUnxPuL1-2-zzQyhbrw04Sh2jQ6v-ljtHCyKHj_dYb8UR3pIPlo_bG9h3PKpf9ujxJ6NbQ1Srun08ibBUmXs7jnMImhAnexk1IjdciFq59YeCsye27wK9nsIfcg4_WF-qg4uy0v',
  },
  {
    id: 'industrial-robot',
    title: 'Precision Industrial Robot Alpha X1',
    category: 'Tech',
    description: 'Heavy duty robotic arms for advanced enterprise mechanics and precise spatial programming. Fully verified setup.',
    sku: 'TECH-ROB-X1',
    currentBid: 41200,
    yourMaxBid: 42500,
    yourBid: 41200,
    totalBids: 14,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBnWsl-pP4TR4t7DiSTkFkLiFEx13SQCBE4T8yoXQiNjG_0y4lFc0jeQFjNPOV3gfEU_TQCCxFc-H_3Ee1mfVDiUy5mToHswZFpwfnbJWhR7jhf0buQWjx9oVoVPQhQdBIt1k2QMvZ7hnA_TBT6cO7VijcYKm9k0utkVym3O4W7uHEPZitXk7tfqfIjK0e3FRXx6Z6kDzD-T2z5oS8E0vaDBVjzG0XqomDsixcREG9C24Nem4XP0v38r9Moa3nKTCplOiM_g86PNf6S',
    timerSeconds: 9900,
    status: 'active',
    condition: 'New',
    sellerName: 'Industrial Robotics',
    sellerRating: 5.0,
    sellerSales: 82,
    sellerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJMliNAX9iwfBs5w9IqD-A5JVNLkceWMpZoXHttDLkZEn9GsuALDInSRPSVqEUs5GGYq5hJYwIMcA_AEsIR1pYOZAPxg1w-vtbzAHQcf7Xd-KYn_4reIVsYn08Nby_mysL-pYseyUnxPuL1-2-zzQyhbrw04Sh2jQ6v-ljtHCyKHj_dYb8UR3pIPlo_bG9h3PKpf9ujxJ6NbQ1Srun08ibBUmXs7jnMImhAnexk1IjdciFq59YeCsye27wK9nsIfcg4_WF-qg4uy0v',
    bidStatus: 'winning'
  },
  {
    id: 'leica-m3-suspect',
    title: 'Vintage Leica M3 Camera',
    category: 'Collectibles',
    description: 'Suspended/flagged camera item for audit verification. Suspected imitation or inaccurate parts.',
    sku: 'FLAG-CAM-03',
    currentBid: 3200,
    totalBids: 18,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAba02c_U-G011ivHcANn2-qUiHJSZ6huX7nsffTuVpan2-IbIoNagYo-2ObkyrdM5eeMS6vhLF_ajPStxGB0VhPtbsKR-7U8Rb2FtCO0Rjl_eAhO3tnqNUnA9-lJIsuYiOErWCPqc9z0Pzc_kDkFj6COi3uahN8pB7NNhy7Bd0EZONQd5INbGsMIRHmMYZhiBCJ61zjc6YbMv-SsbZACc0jYyNwn-qjliP8ZDyuP1e_XmK6evA8AH2WndLChvUZWT5IyBcDRjQTZnF',
    timerSeconds: 0,
    status: 'flagged',
    flagReason: 'Suspected Counterfeit',
    condition: 'Used',
    sellerName: 'RetroVintageShop',
    sellerRating: 3.2,
    sellerSales: 410,
    sellerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJMliNAX9iwfBs5w9IqD-A5JVNLkceWMpZoXHttDLkZEn9GsuALDInSRPSVqEUs5GGYq5hJYwIMcA_AEsIR1pYOZAPxg1w-vtbzAHQcf7Xd-KYn_4reIVsYn08Nby_mysL-pYseyUnxPuL1-2-zzQyhbrw04Sh2jQ6v-ljtHCyKHj_dYb8UR3pIPlo_bG9h3PKpf9ujxJ6NbQ1Srun08ibBUmXs7jnMImhAnexk1IjdciFq59YeCsye27wK9nsIfcg4_WF-qg4uy0v'
  },
  {
    id: 'smartwatch-inaccurate',
    title: 'Modern Smart Watch Pro',
    category: 'Tech',
    description: 'A modern white clean smartwatch in highkey setup. Inaccurate pixel resolution in specs list reported.',
    sku: 'FLAG-SM-PRO',
    currentBid: 120,
    totalBids: 5,
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBXz4MbjjUeOT7JpBEuR1oG9DttRletgopN7kCFaW1640eyWb2RaI0iLEl-O9dSq00FDzn4i-kNNKcyXsPMO6DlFOZFlp5fclPrnF48edO-3aq4qNImB-NE84M0I2PWLBrAR0vavuctGtObKBCG1w_pCNfPcDA0ukTalBJBU53vEU0XVLKGpArn-D5OsqtaxK0xue3z7NZCucyn1HNkLHp-pblDn8KqBjKU5yYPXyI_APlLdNPrPtqUQElP_wHe-COq5tDBHPiJJ2fF',
    timerSeconds: 0,
    status: 'flagged',
    flagReason: 'Inaccurate Description',
    condition: 'New',
    sellerName: 'ShenzhenDirect',
    sellerRating: 4.1,
    sellerSales: 9400,
    sellerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJMliNAX9iwfBs5w9IqD-A5JVNLkceWMpZoXHttDLkZEn9GsuALDInSRPSVqEUs5GGYq5hJYwIMcA_AEsIR1pYOZAPxg1w-vtbzAHQcf7Xd-KYn_4reIVsYn08Nby_mysL-pYseyUnxPuL1-2-zzQyhbrw04Sh2jQ6v-ljtHCyKHj_dYb8UR3pIPlo_bG9h3PKpf9ujxJ6NbQ1Srun08ibBUmXs7jnMImhAnexk1IjdciFq59YeCsye27wK9nsIfcg4_WF-qg4uy0v'
  }
];

